### ISSUE TITLE
Hide/unhide searched setlist looks weird

### ISSUE THREAD

**Issue by MrTengil** [tskarhed/setlist#12]
The button to hide/unhide search list looks weird and I don't like it. It is not clear that this is a button you can interact with. Is it solved by changing opacity to 1?

This is what I mean:
![image](https://user-images.githubusercontent.com/52031625/82731760-5a17d800-9d09-11ea-9616-ecf8013614cf.png)

**Comment by tskarhed** [comment]
This is handled in #6
