### ISSUE TITLE
Login screen improvementss

### ISSUE THREAD

**Issue by MrTengil** [tskarhed/setlist#56]
Remove the green bar at the top as seen below.
![image](https://user-images.githubusercontent.com/52031625/94280305-865c9300-ff4d-11ea-810e-0c211520fabe.png)

The bar makes the login screen look ugly.

Move the buttons on the inlog screen down a little bit. Think in 3rds.

**Comment by MrTengil** [comment]
Skip what I said about moving the buttons down.

**Comment by tskarhed** [comment]
Page is already very complex. Do this in a manner that doesn't make it more complex - alternatively rewrite Page with a pure PageLayout component.
