### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by MrTengil** [tskarhed/setlist#7]
Add possitibilties to add lyrics/sheets to each song.
Make it obvious that lyrics/sheet exsists for the chosen song (toggle on/off whenever there exists a lyric or sheet).
Maybe a link to said lyrics/sheet is enough?
Something like this...
![image](https://user-images.githubusercontent.com/52031625/82704291-81bd6080-9c75-11ea-9efd-ddc30eb6ad0c.png)

**Comment by MrTengil** [comment]
What about having the sheet music link to a Google Drive PDF document?

**Comment by tskarhed** [comment]
Implemented in #21
